### ISSUE TITLE
路由地址出现/#/X:/

### ISSUE THREAD

**Issue by guoyan997** [luojilab/vue-stack-router#24]
使用vue cli3创建的新项目，然后按文档教程设置的路由，npm run serve之后，打开的url都带有/#/X:/，然后router-view无法渲染出来

**Comment by yangcore** [comment]
同样出站此问题

**Comment by leaves4j** [comment]
@guoyan997 @yangcore 并未复现，请提供一下复现集

**Comment by leaves4j** [comment]
fixed in v0.5.1
