### ISSUE TITLE
router.replace 组件没有被销毁destroyed没有被调用，可能造成内存泄漏

### ISSUE THREAD

**Issue by a365344743s** [luojilab/vue-stack-router#31]
**Version**
0.6.1

**Describe the bug**
两个页面互相replace，通过vue-devtools发现被替换的组件没有被销毁，打印日志显示destroyed未被调用，内存显示一直在增长

**To Reproduce**
1. router.replace

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/15245246/81382061-551b2c00-9140-11ea-8887-721a5ca74312.png)
![image](https://user-images.githubusercontent.com/15245246/81382167-85fb6100-9140-11ea-90d0-4ed20d5cbaa4.png)

**Additional context**
我试图在Router.ts的updateRouteRecords中修改代码为这样
![image](https://user-images.githubusercontent.com/15245246/81383830-4f731580-9143-11ea-9ca4-b9998c175bec.png)
这样组件的生命周期调用正常了，但是有时在页面切换的时候在vue-devtools还是会出现两个页面，
![image](https://user-images.githubusercontent.com/15245246/81383975-93661a80-9143-11ea-80d0-8fbbca37558c.png)

**Comment by leaves4j** [comment]
fixed in 0.6.3
